version: '3.8'
services:
  postgres:
    container_name: postgres-pg-mem-server
    image: postgres:15.2
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
